function t132_unifyHeights(){$('.t132__box').children('.t132__wrappper').each(function(){$(this).children('a').children('div').css('width',$(this).outerWidth()-1);$(this).children('a').children('div').css('height',$(this).outerHeight()-40)})}
function t270_scroll(hash,offset){var $root=$('html, body');var target="";try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message)}
if(target.length==0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length==0){return!1}}
$root.animate({scrollTop:target.offset().top-offset},500,function(){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}});return!0}
function t418_checkSize(recid){var el=$("#rec"+recid);var sizer=el.find('.t418__height');var height=sizer.height();var width=sizer.width();var ratio=width/height;var gallerywrapper=el.find(".t418__checksize");var gallerywidth=gallerywrapper.width();gallerywrapper.css({'height':((gallerywidth/ratio)+'px')});var maxwidth=el.find(".t418__height").width();var windowwidth=$(window).width();var value=windowwidth-80;if(maxwidth>windowwidth){el.find(".t418__item").css("max-width",value+"px");el.find(".t418__img").css("left","20px");el.find(".t418__img").css("right","20px")}else{el.find(".t418__item").css("max-width","");el.find(".t418__img").css("left","");el.find(".t418__img").css("right","")}}
function t418_init(recid){var el=$('#rec'+recid);var pos=0;var t418_doResize;var totalSlides=el.find('.t418__item').length;var sliderWidth=el.find('.t418__item').width();$(window).resize(function(){if(t418_doResize)clearTimeout(t418_doResize);t418_doResize=setTimeout(function(){sliderWidth=el.find('.t418__item').width();el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);console.log(sliderWidth)},200)});el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);el.find('.t418__next').click(function(){slideRight(recid)});el.find('.t418__previous').click(function(){slideLeft(recid)});function slideLeft(recid){var el=$('#rec'+recid);pos--;if(pos==-1){pos=totalSlides-1}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
function slideRight(recid){var el=$('#rec'+recid);pos++;if(pos==totalSlides){pos=0}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
var swipeOptions={triggerOnTouchEnd:!0,swipeStatus:swipeStatus,allowPageScroll:"vertical",threshold:75};el.find(".t418__slidecontainer").swipe(swipeOptions);el.find(".t418__slidecontainer").swipe({tap:function(event,target){slideRight(recid)}});function swipeStatus(event,phase,direction,distance){if(phase=="move"&&(direction=="left"||direction=="right")){var duration=0;if(direction=="left"){scrollImages((sliderWidth*pos)+distance,duration)}else if(direction=="right"){scrollImages((sliderWidth*pos)-distance,duration)}}else if(phase=="cancel"){scrollImages(sliderWidth*pos)}else if(phase=="end"){if(direction=="right"){slideLeft(recid)}else if(direction=="left"){slideRight(recid)}}}
function scrollImages(distance,duration){el.find(".t418__slidecontainer").css("transition-duration",(duration/1000).toFixed(1)+"s");var value=(distance<0?"":"-")+Math.abs(distance).toString();el.find(".t418__slidecontainer").css("transform","translate("+value+"px, 0)")}}
function t902_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t902');var doResize;t902_unifyHeights(rec);$(window).resize(function(){clearTimeout(doResize);doResize=setTimeout(function(){t902_unifyHeights(rec)},200)});$(window).load(function(){t902_unifyHeights(rec)});$('.t902').bind('displayChanged',function(){t902_unifyHeights(rec)});if(container.hasClass('t902__previewmode')){setInterval(function(){t902_unifyHeights(rec)},2000)}}
function t902_unifyHeights(rec){if($(window).width()>=960){rec.find('.t902 .t-container .t902__row').each(function(){var highestBox=0;var row=$(this);$('.t902__inner-col',this).each(function(){var col=$(this);var wrap=col.find('.t902__wrap');var colHeight=wrap.outerHeight();if(colHeight>highestBox){highestBox=colHeight}});$('.t902__inner-col',this).css('height',highestBox);$('.t902__bgimg',this).css('height',highestBox)})}else{$('.t902__inner-col').css('height','auto');$('.t902__bgimg').css('height','auto')}
t902_setMinHeight(rec)}
function t902_setMinHeight(rec){var forEach=function(array,callback,scope){for(var i=0;i<array.length;i++){callback.call(scope,i,array[i])}};var wrappers=t902_getWrappers(rec);forEach(wrappers,function(index,wrapper){var content=wrapper.querySelector('.t902__content');if(wrapper.offsetHeight<content.offsetHeight){wrapper.style.minHeight=content.offsetHeight+'px'}})}
function t902_getWrappers(rec){var el=rec[0];var wrappers=el.querySelectorAll('.t902__wrap');return wrappers}